export const PROVINCES = [
  { name: 'An Giang', slug: 'an-giang', region: 'Miền Nam' },
  { name: 'Bà Rịa - Vũng Tàu', slug: 'ba-ria-vung-tau', region: 'Miền Nam' },
  { name: 'Bắc Giang', slug: 'bac-giang', region: 'Miền Bắc' },
  { name: 'Bắc Kạn', slug: 'bac-kan', region: 'Miền Bắc' },
  { name: 'Bạc Liêu', slug: 'bac-lieu', region: 'Miền Nam' },
  { name: 'Bắc Ninh', slug: 'bac-ninh', region: 'Miền Bắc' },
  { name: 'Bến Tre', slug: 'ben-tre', region: 'Miền Nam' },
  { name: 'Bình Định', slug: 'binh-dinh', region: 'Miền Trung' },
  { name: 'Bình Dương', slug: 'binh-duong', region: 'Miền Nam' },
  { name: 'Bình Phước', slug: 'binh-phuoc', region: 'Miền Nam' },
  { name: 'Bình Thuận', slug: 'binh-thuan', region: 'Miền Nam' },
  { name: 'Cà Mau', slug: 'ca-mau', region: 'Miền Nam' },
  { name: 'Cao Bằng', slug: 'cao-bang', region: 'Miền Bắc' },
  { name: 'Đắk Lắk', slug: 'dak-lak', region: 'Miền Trung' },
  { name: 'Đắk Nông', slug: 'dak-nong', region: 'Miền Trung' },
  { name: 'Điện Biên', slug: 'dien-bien', region: 'Miền Bắc' },
  { name: 'Đồng Nai', slug: 'dong-nai', region: 'Miền Nam' },
  { name: 'Đồng Tháp', slug: 'dong-thap', region: 'Miền Nam' },
  { name: 'Gia Lai', slug: 'gia-lai', region: 'Miền Trung' },
  { name: 'Hà Giang', slug: 'ha-giang', region: 'Miền Bắc' },
  { name: 'Hà Nam', slug: 'ha-nam', region: 'Miền Bắc' },
  { name: 'Hà Tĩnh', slug: 'ha-tinh', region: 'Miền Trung' },
  { name: 'Hải Dương', slug: 'hai-duong', region: 'Miền Bắc' },
  { name: 'Hậu Giang', slug: 'hau-giang', region: 'Miền Nam' },
  { name: 'Hòa Bình', slug: 'hoa-binh', region: 'Miền Bắc' },
  { name: 'Hưng Yên', slug: 'hung-yen', region: 'Miền Bắc' },
  { name: 'Khánh Hòa', slug: 'khanh-hoa', region: 'Miền Trung' },
  { name: 'Kiên Giang', slug: 'kien-giang', region: 'Miền Nam' },
  { name: 'Kon Tum', slug: 'kon-tum', region: 'Miền Trung' },
  { name: 'Lai Châu', slug: 'lai-chau', region: 'Miền Bắc' },
  { name: 'Lâm Đồng', slug: 'lam-dong', region: 'Miền Trung' },
  { name: 'Lạng Sơn', slug: 'lang-son', region: 'Miền Bắc' },
  { name: 'Lào Cai', slug: 'lao-cai', region: 'Miền Bắc' },
  { name: 'Long An', slug: 'long-an', region: 'Miền Nam' },
  { name: 'Nam Định', slug: 'nam-dinh', region: 'Miền Bắc' },
  { name: 'Nghệ An', slug: 'nghe-an', region: 'Miền Trung' },
  { name: 'Ninh Bình', slug: 'ninh-binh', region: 'Miền Bắc' },
  { name: 'Ninh Thuận', slug: 'ninh-thuan', region: 'Miền Trung' },
  { name: 'Phú Thọ', slug: 'phu-tho', region: 'Miền Bắc' },
  { name: 'Phú Yên', slug: 'phu-yen', region: 'Miền Trung' },
  { name: 'Quảng Bình', slug: 'quang-binh', region: 'Miền Trung' },
  { name: 'Quảng Nam', slug: 'quang-nam', region: 'Miền Trung' },
  { name: 'Quảng Ngãi', slug: 'quang-ngai', region: 'Miền Trung' },
  { name: 'Quảng Ninh', slug: 'quang-ninh', region: 'Miền Bắc' },
  { name: 'Quảng Trị', slug: 'quang-tri', region: 'Miền Trung' },
  { name: 'Sóc Trăng', slug: 'soc-trang', region: 'Miền Nam' },
  { name: 'Sơn La', slug: 'son-la', region: 'Miền Bắc' },
  { name: 'Tây Ninh', slug: 'tay-ninh', region: 'Miền Nam' },
  { name: 'Thái Bình', slug: 'thai-binh', region: 'Miền Bắc' },
  { name: 'Thái Nguyên', slug: 'thai-nguyen', region: 'Miền Bắc' },
  { name: 'Thanh Hóa', slug: 'thanh-hoa', region: 'Miền Trung' },
  { name: 'Thừa Thiên Huế', slug: 'thua-thien-hue', region: 'Miền Trung' },
  { name: 'Tiền Giang', slug: 'tien-giang', region: 'Miền Nam' },
  { name: 'Trà Vinh', slug: 'tra-vinh', region: 'Miền Nam' },
  { name: 'Tuyên Quang', slug: 'tuyen-quang', region: 'Miền Bắc' },
  { name: 'Vĩnh Long', slug: 'vinh-long', region: 'Miền Nam' },
  { name: 'Vĩnh Phúc', slug: 'vinh-phuc', region: 'Miền Bắc' },
  { name: 'Yên Bái', slug: 'yen-bai', region: 'Miền Bắc' },
  { name: 'Hà Nội', slug: 'ha-noi', region: 'Miền Bắc' },
  { name: 'Hồ Chí Minh', slug: 'ho-chi-minh', region: 'Miền Nam' },
  { name: 'Hải Phòng', slug: 'hai-phong', region: 'Miền Bắc' },
  { name: 'Đà Nẵng', slug: 'da-nang', region: 'Miền Trung' },
  { name: 'Cần Thơ', slug: 'can-tho', region: 'Miền Nam' }
];

export const REGIONS = [
  { name: 'Miền Bắc', slug: 'mien-bac', code: 'bac' },
  { name: 'Miền Trung', slug: 'mien-trung', code: 'trung' },
  { name: 'Miền Nam', slug: 'mien-nam', code: 'nam' }
];

// Danh sách nghề thiên về giới trẻ để hiển thị mặc định
export const DEFAULT_OCCUPATIONS = [
  'Sinh viên',
  'Học sinh',
  'Người mẫu',
  'Diễn viên',
  'Ca sĩ',
  'Photographer',
  'Makeup artist',
  'Stylist',
  'Blogger',
  'Freelancer',
  'Nhân viên bán hàng',
  'Nhân viên văn phòng'
];

export const DEFAULT_TAGS = [
  'Da trắng',
  'Chân dài',
  'Dễ thương',
  'Gợi cảm',
  'Năng động',
  'Dịu dàng',
  'Cá tính',
  'Thân thiện'
];

export const ITEMS_PER_PAGE = 24;
export const FEATURED_ITEMS_COUNT = 12;